### PR TITLE
Update steelseries-gg from 32.1.0 to 33.0.0

### PR DESCRIPTION
**Pull request by razvanazamfirei**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@razvanazamfirei After this fails I will rerun CI in debug mode so we get a bit more information about the failure.

**Comment by bevanjkay** [comment]
@dduugg Are you able to help debug what is happening here? Seems relevant to Brew#14769

```
Error: undefined method `keys' for #<Array:0x00007f90224538a0>
Do not report this issue until you've run `brew update` and tried again.
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_artifact.rb:116:in `read_script_arguments'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:317:in `uninstall_script'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:79:in `dispatch_uninstall_directive'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:15:in `block in uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `uninstall_phase'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:463:in `block in uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:460:in `uninstall_artifacts'
/usr/local/Homebrew/Library/Homebrew/cask/installer.rb:402:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:44:in `block in uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `each'
/usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `uninstall_casks'
/usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:79:in `uninstall'
/usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
Error: Process completed with exit code 1.
```

**Comment by razvanazamfirei** [comment]
> @dduugg Are you able to help debug what is happening here? Seems relevant to [Brew#14769](https://github.com/Homebrew/brew/pull/14769)
> 
> https://github.com/Homebrew/homebrew-cask-drivers/actions/runs/4353769349/jobs/7608370136#step:18:410
> 
> ```
> Error: undefined method `keys' for #<Array:0x00007f90224538a0>
> Do not report this issue until you've run `brew update` and tried again.
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_artifact.rb:116:in `read_script_arguments'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:317:in `uninstall_script'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/abstract_uninstall.rb:79:in `dispatch_uninstall_directive'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:15:in `block in uninstall_phase'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact/uninstall.rb:14:in `uninstall_phase'
> /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:463:in `block in uninstall_artifacts'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/artifact_set.rb:14:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:460:in `uninstall_artifacts'
> /usr/local/Homebrew/Library/Homebrew/cask/installer.rb:402:in `uninstall'
> /usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:44:in `block in uninstall_casks'
> /usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `each'
> /usr/local/Homebrew/Library/Homebrew/cask/cmd/uninstall.rb:39:in `uninstall_casks'
> /usr/local/Homebrew/Library/Homebrew/cmd/uninstall.rb:79:in `uninstall'
> /usr/local/Homebrew/Library/Homebrew/brew.rb:93:in `<main>'
> Error: Process completed with exit code 1.
> ```

Trying to debug it.

**Comment by dduugg** [comment]
I'm not sure what's going on, but try with this patch, which reverts the recent change to the line implicated in `abstract_uninstall`: https://github.com/Homebrew/brew/pull/14914

**Review by p-linnane — APPROVED** [review]

**Comment by bevanjkay** [comment]
Thanks @dduugg

**Pull request merged**
