### PR TITLE
Update silicon-labs-vcp-driver from 5.1.0 to 5.2.0

### PR DESCRIPTION
**Pull request by henry-y-c**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> pkg source file not found: 'Silicon Labs VCP Driver.pkg'

It’s failing due to not finding a source to install. We have [documentation on how to fix it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

**Comment by henry-y-c** [comment]
> > pkg source file not found: 'Silicon Labs VCP Driver.pkg'
> 
> It’s failing due to not finding a source to install. We have [documentation on how to fix it](https://github.com/Homebrew/homebrew-cask/blob/master/doc/reporting_bugs/source_is_not_there_error.md).

Updated PR replacing `pkg` with `app`, still failed to locate the .app file.

**Comment by vitorgalvao** [comment]
> It seems the App source '/usr/local/Caskroom/silicon-labs-vcp-driver/5.2.0/⁨Install CP210x VCP Driver.app⁩' is not there.

Which means you’re still pointing to the wrong thing.

**Comment by kquinsland** [comment]
I just got bit by this as well.

The `zip` contains a `dmg` which does have a `Install CP210x VCP Driver.app` in it's root.

**Comment by henry-y-c** [comment]
@vitorgalvao Didn't know about `install manual` for the `.app` file. Thanks! I learnt something new :)

**Comment by henry-y-c** [comment]
> I just got bit by this as well.
> 
> The `zip` contains a `dmg` which does have a `Install CP210x VCP Driver.app` in it's root.

As @vitorgalvao suggested in his commit, by marking the `Install CP210x VCP Driver.app` as manual install, it passes the CI.

However, I don't see the necessity of using brew cask to manage this driver if I still need to manually install/uninstall in UI. For now, I would just close this PR and run some tests locally b4 finding an automated solution.

@kquinsland Lemme know if u find a better way to solve this.

**Comment by vitorgalvao** [comment]
> However, I don't see the necessity of using brew cask to manage this driver if I still need to manually install/uninstall in UI.

You don’t need to download it an unpack it yourself and you get access to an uninstallation and `zap` procedure.

**Comment by henry-y-c** [comment]
> > However, I don't see the necessity of using brew cask to manage this driver if I still need to manually install/uninstall in UI.
> 
> You don’t need to download it an unpack it yourself and you get access to an uninstallation and `zap` procedure.

That's true.
I saw the PR #1095 has been approved 2 days ago. Could that automate the installation/uninstallation in terminal?

**Comment by vitorgalvao** [comment]
> Could that automate the installation/uninstallation in terminal?

Yes.

**Pull request closed without merging**
