### PR TITLE
Update behringer-x32-edit.rb

### PR DESCRIPTION
**Pull request by suschizu**
would it be possible to use the whole version for this cask? 
we already had 4.0.1 - and 4.0.3 is the newest

### CODE REVIEW

**Comment by suschizu** [comment]
I'm not sure what problem travis has with the style

**Comment by vitorgalvao** [comment]
Apparently there are conflicts we can’t resolve from the web interface. Going to do it from another PR: https://github.com/Homebrew/homebrew-cask-drivers/pull/1355.

**Comment by suschizu** [comment]
I closed it because version 4.1 was already merged

**Comment by vitorgalvao** [comment]
> I closed it because version 4.1 was already merged

Yes, but the rest of your changes were also good, so it makes sense to include them. Looks like the `style` bug in CI is resolved.

**Pull request closed without merging**
