### PR TITLE
Update blue-sherpa from 20191122 to 20200810

### PR DESCRIPTION
**Pull request by ran-dall**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Created with [`cask-repair`](https://github.com/Homebrew/homebrew-cask/blob/master/CONTRIBUTING.md#updating-a-cask).

### CODE REVIEW

**Comment by miccal** [comment]
This is timing out because the `.pkg` runs a preinstall script `BlueSherpa-20200810.pkg/Blue.pkg/Scripts/preinstall` that calls a GUI:

Screen Shot 2020-09-20 at 23 17 37

Not sure how to get this to run on the CI.

**Comment by reitermarkus** [comment]
I think this should be `installer manual` since it will also block while the GUI is open locally, right?

**Comment by miccal** [comment]
> I think this should be `installer manual` since it will also block while the GUI is open locally, right?

I believe you are correct @reitermarkus.

**Review by miccal — APPROVED** [review]

**Pull request merged**
