### PR TITLE
Add eObčanka

### PR DESCRIPTION
**Pull request by krystof-k**
Add [eObčanka](https://info.identitaobcana.cz/eop/InstalacemacOS.aspx), Czech national ID, app.

---

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
   Note: It make more sense to ommit the vendor as it would have to be be something like `czech` etc., `eobcanka` (meaning `eidcard` in Czech) seems fine to me.
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask <cask>` worked successfully.
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by carlocab** [comment]
Shouldn't this be submitted to https://github.com/Homebrew/homebrew-cask? This doesn't look like a device driver, or similar. (I don't speak Czech, though, so I could be mistaken.)

**Comment by krystof-k** [comment]
I was following "_If the software is useless without the peripheral, it’s considered a driver._", as if you don't have the national ID card _pheripheral_, it is useless :) But I guess the regular cask repo is fine as well.

**Comment by carlocab** [comment]
I see; that makes sense. That's a good fit for this repo then.

**Comment by miccal** [comment]
Thank you @krystof-k.

**Pull request merged**
