### PR TITLE
Update logitech-unifying 1.3.375 version and zap

### PR DESCRIPTION
**Pull request by ytbmulder**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by reitermarkus** [comment]
Do you personally need the old versions?

**Comment by ytbmulder** [comment]
> Do you personally need the old versions?

I do personally need version `1.2.359` for `yosemite`. I removed the version for `mavericks`.

**Comment by claui** [comment]
Thanks @ytbmulder!

**Comment by ytbmulder** [comment]
> Thanks @ytbmulder!

Always a pleasure :)

**Pull request merged**
