### PR TITLE
Update wacom-tablet to 6.4.0-9

### PR DESCRIPTION
**Pull request by Mr-TTOT**
Update & attempt to simplify uninstall to troubleshoot https://github.com/Homebrew/homebrew-cask-drivers/pull/3073

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [X] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [X] `brew audit --cask --online <cask>` is error-free.
- [X] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by Mr-TTOT** [comment]
Thanks for the update! Is there any more info on the reason for the apparent UUIDs added to the end? Curious if it's intentional new behavior or something unexpected.

Related to contributing: is there a way to run the integration tests locally before submitting a PR? And is there any other more extensive doc than [the Cask Cookbook](https://docs.brew.sh/Cask-Cookbook) for designing the uninstall and livecheck stanzas?

**Comment by p-linnane** [comment]
@Mr-TTOT You can check this out for `livecheck`: https://docs.brew.sh/Brew-Livecheck

**Comment by iamjoeysox** [comment]
Any updates on this?

**Comment by bevanjkay** [comment]
@iamjoeysox I will hopefully have some time tomorrow to have a look at the dependent PR.

**Comment by iamjoeysox** [comment]
> @iamjoeysox I will hopefully have some time tomorrow to have a look at the dependent PR.

Hey buddy, let me know if there is anything I can do to help out, this keeps causing me headaches with clients haha. Thanks again!

**Comment by bevanjkay** [comment]
@Mr-TTOT I've spent some time on it today and I think it should be very close now. I've never written tests for Ruby, so it's been a learning curve

**Comment by iamjoeysox** [comment]
> @iamjoeysox I've spent some time on it today and I think it should be very close now. I've never written tests for Ruby, so it's been a learning curve

That's awesome news! No worries, I totally understand. 😄

**Review by p-linnane — APPROVED** [review]
Thank you to @bevanjkay for all the hard work getting this over the line!

**Pull request merged**
