### PR TITLE
Update flashforge-flashprint from 4.5.1 to 5.3.3

### PR DESCRIPTION
**Pull request by kennedyshead**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by bevanjkay** [comment]
@kennedyshead CI will still fail because there is no livecheck. I'll have a little look now, because I don't think it's going to be super straight forward (in which case we may use a livecheck skip block instead).

**Comment by kennedyshead** [comment]
This is correct sha 01908dc35bfb8b2fbf812caabac070dc0a788d99b1179ce2495996e818c07dbc just checked locally

**Comment by kennedyshead** [comment]
Also I guess we need to handle that uninstall version thing?

**Comment by bevanjkay** [comment]
@kennedyshead I have made a couple of changes which I will explain.

The new URL is the one that you are directed to when initiating an in-app update. This URL is easier to work with because it only uses the main application version, and not a hash for the download link, meaning we can more easily check for a new version with `livecheck`.

I removed `auto_updates true` because although there is an in-built mechanism to download a new version, it requires manual installation.

**Comment by kennedyshead** [comment]
> @kennedyshead I have made a couple of changes which I will explain.
> 
> The new URL is the one that you are directed to when initiating an in-app update. This URL is easier to work with because it only uses the main application version, and not a hash for the download link, meaning we can more easily check for a new version with `livecheck`.
> 
> I removed `auto_updates true` because although there is an in-built mechanism to download a new version, it requires manual installation.

Nice! Thank you for education! First one for this (and I also think ruby :D )

**Pull request merged**
