### PR TITLE
add displaylink v1.3

### PR DESCRIPTION
**Pull request by Kami-no**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew install --cask {{cask_file}}` worked successfully.
- [ ] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by Kami-no** [comment]
How could I test it locally?

**Comment by miccal** [comment]
Not really sure what is going on here:
```
Error: Could not find PKG source file 'DisplayLink Manager Graphics Connectivity 1.3.pkg', found 'DisplayLinkManagerApp.pkg' instead.
```
The `url` downloads `DisplayLink Manager Graphics Connectivity 1.3.pkg`.

**Comment by Muxelmann** [comment]
Using `pkgutil` on the downloaded `DisplayLink Manager Graphics Connectivity 1.3`, I found that it contains `DisplayLinkManagerApp.pkg`:

```
$ cd ~/Downloads
$ ls
DisplayLink Manager Graphics Connectivity 1.3.pkg
$ pkgutil --expand DisplayLink\ Manager\ Graphics\ Connectivity\ 1.3.pkg tmp_dir
$ ls tmp_dir
DisplayLinkManagerApp.pkg	Distribution			Resources
```

Not sure if the package gets expanded before running the setup, but maybe that's what's causing the issue?

**Comment by Muxelmann** [comment]
Looks like 3.1.1, 4.3.1 and 5.2.5 all download a `*.dmg` containing the `DisplayLink Software Installer.pkg`. For Version 1.3, however, a `*.pkg` is downloaded that contains `DisplayLinkManagerApp.pkg`.

**Comment by sheldonhull** [comment]
In case it helps, I found that the new approach doesn't work yet for me on 11.2.3, had to revert back to the older 5* version.

The new approach is moving away from a system extension, and will be eventually distributed through the App Store I believe. It's a different approach altogether based on my reading of the release notes.

**Comment by miccal** [comment]
Closing in favour of https://github.com/Homebrew/homebrew-cask-drivers/pull/2089.

**Pull request closed without merging**
