### PR TITLE
various: migrate remaining casks

### PR DESCRIPTION
**Pull request by razvanazamfirei**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making any changes to a cask, existing or new, verify:

- [ ] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [ ] `brew audit --cask --online <cask>` is error-free.
- [ ] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
- [ ] `brew install --cask <cask>` worked successfully.
- [ ] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by razvanazamfirei** [comment]
How do we fix CI syntax issues when there are no casks left?

**Comment by reitermarkus** [comment]
I guess just delete the CI workflow, since it won't be needed anymore.

**Comment by reitermarkus** [comment]
Or fix the error it in `brew audit`.

**Comment by bevanjkay** [comment]
@reitermarkus I have tried removing the CI workflow, because it won't run against any files anymore. We still wont be able to merge unless someone with permission turns off the required "conclusion" step.

**Comment by reitermarkus** [comment]
We'll need to keep the worfklow, actually, but remove everything except the `conclusion` task.

**Comment by reitermarkus** [comment]
I meant removing the task from the workflow, but we can of course also remove the required status check instead.

**Comment by reitermarkus** [comment]
Needs a rebase.

**Comment by razvanazamfirei** [comment]
All done, @reitermarkus!

**Review by reitermarkus — APPROVED** [review]

**Pull request merged**
