### PR TITLE
Update corsair-icue from 3.12.118 to 3.14.104

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ytbmulder** [comment]
@suschizu This problem
```
audit for corsair-icue: failed
 - The URL https://www.corsair.com/ is not reachable (HTTP status code 403)
```
 was also present when I added this cask: https://github.com/Homebrew/homebrew-cask-drivers/pull/783.

On a side note, could you remove the extra `/` in the `url`?

**Comment by suschizu** [comment]
ah thanks for tip - I thought the missing / could be a problem too

**Comment by suschizu** [comment]
the audit passed locally

**Comment by ytbmulder** [comment]
> the audit test passed locally

Was this with or without the double `/` in the `url`?

**Comment by suschizu** [comment]
hey @ytbmulder - I did the audit check with the latest update - passed again 
I thought that the homepage always has to end with a / (?)
which // you mean in the url?

**Comment by ytbmulder** [comment]
> hey @ytbmulder - I did the audit check with the latest update - passed again
> I thought that the homepage always has to end with a / (?)
> which // you mean in the url?

You are right, my bad. Two `/` are expected.

**Comment by suschizu** [comment]
ok - so 
the homepage "https://www.corsair.com/us/en/icue/" isn't working
I changed it now to "https://www.corsair.com/" 
audit passed again

**Comment by ytbmulder** [comment]
> ok - so
> the homepage "https://www.corsair.com/us/en/icue/" isn't working
> I changed it now to "https://www.corsair.com/"
> audit passed again

I would prefer to keep the `url` as at was. Since now it points to the brand website, instead of the software website.

@vitorgalvao Maybe you can take a look at the failing `url` and decide if this can be merged or not?

**Pull request merged**
