### PR TITLE
adding camengine utility

### PR DESCRIPTION
**Pull request by alexg0**
_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://docs.brew.sh/Cask-Cookbook#token-reference).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://docs.brew.sh/Acceptable-Casks#finding-a-home-for-your-cask).
- [ ] `brew audit --new-cask <cask>` worked successfully.
   - don't have working livecheck
- [x] `brew install --cask <cask>` worked successfully.
- [x] `brew uninstall --cask <cask>` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
```
/usr/bin/sudo -E -- /usr/bin/env LOGNAME=runner USER=runner USERNAME=runner /usr/sbin/installer -pkg /usr/local/Caskroom/camengine/4.0.63.2,21102201/Step2.CamEngineV4_v4.0.63.2_21102201.pkg -target /
==> Installing artifact of class Cask::Artifact::Pkg
==> Running installer for camengine; your password may be necessary.
Package installers may write to any location; options such as `--appdir` are ignored.
Error: The action has timed out.
```
@alexg0 does the `.pkg` installer require some sort of user intervention to install?

**Comment by alexg0** [comment]
@miccal apparently pkg installer was asking for anonymous usage permission.  Skipped the prompt with `:choices` hash.

**Comment by miccal** [comment]
Thank you @alexg0.

Does the `.dmg` file inside the `.zip`, namely `Step1.Firmware Updater_FW 0.0.8000.46.dmg`, also need to be installed for this to work?

**Comment by alexg0** [comment]
@miccal The zip file is a firmware updater.  It does not seem to work, so I am not so I am not installing it.

**Comment by miccal** [comment]
Thank you @alexg0.

**Pull request merged**
