### PR TITLE
Canon Scanner ICA Drivers

### PR DESCRIPTION
**Pull request by sparhomenko**
- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version (_includes the name but not the version as multiple casks with different versions are involved_).
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] Named the cask according to the [token reference] (_based on `/Library/Image Capture/DevicesCanon IJScanner#{n}.app` installed by these casks_).
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-drivers/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask

#1237, while intended to be a version bump, effectively replaced `canon-pixma-scanner-driver-ica` with the driver intended for completely different models. This seems to be an unfortunate side effect of Canon's approach of providing driver builds for different subsets of their model lineup. This PR tries to reflect that by replacing the cask with with one for each build I was able to find. These casks were [generated](https://github.com/sparhomenko/homebrew-tap/blob/master/canon-ijscanner.rb) from the same template - any advice on a better approach is appreciated.

Please feel free to reject if you feel the complexity outweighs the usefulness. Note though that the current cask is only covering few Canon scanner models (`16f` build variant) and might not be useful to that many users.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Using `token`, while smart, is something I’d prefer we avoided.

**Comment by sparhomenko** [comment]
Updated not to use `#{token}`. Do I understand correctly that the only way to make CI happy would be to split this into separate PRs for each cask?

**Comment by varenc** [comment]
thanks for this! I always feel more secure installing random software through homebrew.

Though what is the correct way to find these?  I did a brew search for `canon` and then found all these different Casks.  I then searched this PR for mention of my model number, MG2900, and found `canon-ijscanner14f`

I now realize I could have found the right one with `brew search --desc MG2900`. Casks don't have descriptions, but I guess that `--desc` flag searches the name with Casks. Is searching with `--desc` just the only way to find the right drivers?

**Comment by sparhomenko** [comment]
You're welcome, it's nice to know this is actually useful for someone.

For finding I don't see an easier way than `brew search --desc`, and even that won't work if you model is eg. MG2920. The most reliable way is to check [Canon website](https://www.usa.canon.com/internet/portal/us/home/support/details/printers/inkjet-multifunction/mg-series-inkjet/mg2920?subtab=downloads-drivers). Look for ICA Driver, if you see `ijscanner14f` in the file name - `canon-ijscanner14f` is your cask.

**Comment by vitorgalvao** [comment]
> I always feel more secure installing random software through homebrew.

Don’t. We actively discourage that attitude. We’re limited unpaid human volunteers, not above making mistakes or being duped. You should do your due diligence and verify what you install through us. Doing so will improve the security of everyone.

**Comment by varenc** [comment]
> Don’t. We actively discourage that attitude. We’re limited unpaid human volunteers, not above making mistakes or being duped. You should do your due diligence and verify what you install through us. Doing so will improve the security of everyone.

Noted! It's at least a signal that aids in my due diligence process, but I can see how that's slippery line and it's important to over index on that.  
By that comment I also was thinking of the clean uninstall/zap stanzas that Casks include to varying degrees. And they definitely aren't perfect, but they're way better than dragging an .app to trash. And looking at the uninstall stanza in a Cask before I install it gives me some useful signal about what it's going to be doing.

**Pull request merged**
