### PR TITLE
Add canon-eos-webcam-utility

### PR DESCRIPTION
**Pull request by leafac**
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
The initial `uninstall: script` calls a GUI and cannot b automated, so I have addedd a manual `uninstall` by inspecting the `.pkg` and the scripts inside the `EOS Webcam Utility Uninstaller.app`.

**Comment by vitorgalvao** [comment]
> so I have added a manual `uninstall` by inspecting the `.pkg` and the scripts inside the `EOS Webcam Utility Uninstaller.app`.

Nice work! It looks correct and passes CI, so no need to check anything, I trust your skill.

**Review by vitorgalvao — APPROVED** [review]

**Comment by miccal** [comment]
> Nice work! It looks correct and passes CI, so no need to check anything, I trust your skill.

Thanks @vitorgalvao.

**Comment by leafac** [comment]
Thank you all!

**Pull request merged**
