### PR TITLE
Update and rename nvidia-cuda to nvidia-cuda-toolkit

### PR DESCRIPTION
**Pull request by m416kar98k**
The cask is for https://developer.nvidia.com/cuda-toolkit not for https://www.nvidia.com/en-us/drivers/cuda.
The relation between CUDA toolkit and CUDA driver is similar with Anaconda and JDK vs Miniconda and JRE.

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-drivers/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by m416kar98k** [comment]
@miccal Thank you for updating, but I would not recommend update the cask to 10.2. Check https://developer.nvidia.com/rdp/cudnn-archive. NVIDIA has dropped CUDNN support for CUDA 10.2 for macOS. The highest stable version is CUDA 10.1.

**Comment by miccal** [comment]
> @miccal
> 
> Thank you for updating, but I would not recommend update the cask to 10.2. Check https://developer.nvidia.com/rdp/cudnn-archive. NVIDIA has dropped CUDNN support for macOS CUDA 10.2. The highest stable version for macOS is CUDA 10.1. It is necessary to install CUDNN support for most of MATLAB and Python API. I believe CUDA 10.2 for macOS is only for sample display not for high performance computation. I am going to submit another cask for CUDA driver only. Usually NVIDIA does not include the latest CUDA driver in their CUDA Toolkit.

Apologies @m416kar98k -- so which version of 10.1 should be used, 10.1.243, 10.1.168 or 10.1.105?

**Comment by m416kar98k** [comment]
> > @miccal
> > Thank you for updating, but I would not recommend update the cask to 10.2. Check https://developer.nvidia.com/rdp/cudnn-archive. NVIDIA has dropped CUDNN support for macOS CUDA 10.2. The highest stable version for macOS is CUDA 10.1. It is necessary to install CUDNN support for most of MATLAB and Python API. I believe CUDA 10.2 for macOS is only for sample display not for high performance computation. I am going to submit another cask for CUDA driver only. Usually NVIDIA does not include the latest CUDA driver in their CUDA Toolkit.
> 
> Apologies @m416kar98k -- so which version of 10.1 should be used, 10.1.243, 10.1.168 or 10.1.105?

I would recommend use 10.1 update 2, which is 10.1.243. I am reinstalling the cask to verify the situation.

**Review by reitermarkus — APPROVED** [review]

**Comment by miccal** [comment]
Thank you for your contribution @m416kar98k.

**Pull request merged**
