### PR TITLE
Replace nordic-nrf5x-command-line-tools.rb with nordic-nrf-command-li…

### PR DESCRIPTION
**Pull request by ytbmulder**
…ne-tools.rb

After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Currently the binaries are taken out, since with this release they are located inside: `nRF-Command-Line-Tools_10_2_1_OSX.tar`. This archive should first be extracted before linking.

### CODE REVIEW

**Comment by ytbmulder** [comment]
@vitorgalvao I didn't see my PR tries to solve the same problem as PR #1058.
However, I believe a cask name change is appropriate, since Nordic Semi removed the `5x` from the software name.

**Comment by vitorgalvao** [comment]
> Currently the binaries are taken out, since with this release they are located inside: `nRF-Command-Line-Tools_10_2_1_OSX.tar`. This archive should first be extracted before linking.

What’s the problem? Isn’t it extracted automatically?

**Comment by ytbmulder** [comment]
> > Currently the binaries are taken out, since with this release they are located inside: `nRF-Command-Line-Tools_10_2_1_OSX.tar`. This archive should first be extracted before linking.
> 
> What’s the problem? Isn’t it extracted automatically?

I enabled the binaries again. At least locally it didn't want to link them.

**Comment by ytbmulder** [comment]
> > Currently the binaries are taken out, since with this release they are located inside: `nRF-Command-Line-Tools_10_2_1_OSX.tar`. This archive should first be extracted before linking.
> 
> What’s the problem? Isn’t it extracted automatically?

This is also what I saw locally:
`It seems the symlink source '/usr/local/Caskroom/nordic-nrf-command-line-tools/10.2.1/nrfjprog/nrfjprog' is not there.`

**Pull request merged**
