### PR TITLE
Update Saleae Logic

### PR DESCRIPTION
**Pull request by alxrey**
Major software's update. **The uninstall stanza should be checked by someone more experienced.**

- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [X] `brew audit --cask {{cask_file}}` is error-free.
- [X] `brew style --fix {{cask_file}}` reports no offenses.

### CODE REVIEW

**Comment by miccal** [comment]
Ping @vitorgalvao regarding the token reference.

**Comment by vitorgalvao** [comment]
> Ping @vitorgalvao regarding the token reference.

In case you’re forgetting, [this repo has an extra rule](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/CONTRIBUTING.md#naming-driver-casks) (and coincidentally, this cask is used as an example).

**Review by vitorgalvao — DISMISSED** [review]

**Review by vitorgalvao — APPROVED** [review]

**Comment by miccal** [comment]
Thank you @alxrey.

@vitorgalvao thanks for that -- I was not certain it it should be called `saleae-logic2` now because of the `app "Logic#{version.major}.app"`.

**Comment by vitorgalvao** [comment]
> I was not certain it it should be called `saleae-logic2` now

Version number are ignored. Only numbers allowed are in `# NOTE: "2" is not a version number, but an intrinsic part of the product name` situations, such as `convert-mp3`.

**Pull request merged**
