### PR TITLE
Update synology-cloud-station-backup to 4.3.0-4435

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by suschizu** [comment]
I'm not sure what is the problem here: 
I've already added com.synology.CloudStationBackupUI to uninstall quit

**Comment by ytbmulder** [comment]
> I'm not sure what is the problem here:
> I've already added com.synology.CloudStationBackupUI to uninstall quit

Some applications do not completely shut down when used with the `quit` stanza. 
You could try using `signal` instead:
```
signal: ['TERM', 'com.ubnt.UniFi'],
```
See `ubiquiti-unifi-controller.rb` for an [example](https://github.com/Homebrew/homebrew-cask-drivers/blob/master/Casks/ubiquiti-unifi-controller.rb#L23).

**Comment by ytbmulder** [comment]
My mistake, you should put the Synology ID in the `signal` stanza.

**Comment by suschizu** [comment]
@ytbmulder - thanks for your help :) Seems to be ok now

**Comment by ytbmulder** [comment]
I see that the other ID is also still running. You can remove the two IDs from the `quit` stanza and add them both to the `signal` stanza:
```
launchctl: 'com.synology.Synology Cloud Station Backup',
signal:    [
                ['TERM', 'com.synology.CloudStationBackupUI'],
                ['TERM', 'com.synology.CloudStationBackup'],
           ],
```

**Comment by suschizu** [comment]
thanks again - hopefully the last commit :)

**Pull request merged**
