### PR TITLE
Update hdhomerun from 20220303 to 20220822

### PR DESCRIPTION
**Pull request by owine**
Created by `brew bump`

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by owine** [comment]
The installer opens a Terminal window to run a firmware upgrade package. I added Terminal to the uninstall quit stanza to pass CI, but I am not sure if that is ideal.

**Comment by carlocab** [comment]
> I added Terminal to the uninstall quit stanza to pass CI, but I am not sure if that is ideal.

Will this quit a Terminal window the user has open?

**Comment by owine** [comment]
> > I added Terminal to the uninstall quit stanza to pass CI, but I am not sure if that is ideal.
> 
> Will this quit a Terminal window the user has open?

I would imagine it would, yes.

**Comment by carlocab** [comment]
Oh, not nice. @Homebrew/cask, ideas?

**Comment by miccal** [comment]
Perhaps add `Terminal` like @reitermarkus did for `Preview` in https://github.com/Homebrew/homebrew-cask/pull/129758?

**Pull request merged**
