### PR TITLE
Update asix-ax88179 v2.18.0 to correct URL

### PR DESCRIPTION
**Pull request by junian**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask-drivers/pulls) for the same update.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, **if adding a new cask**:

- [ ] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [ ] `brew cask audit --new-cask {{cask_file}}` worked successfully.
- [ ] `brew cask install {{cask_file}}` worked successfully.
- [ ] `brew cask uninstall {{cask_file}}` worked successfully.
- [ ] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [ ] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).

### CODE REVIEW

**Comment by miccal** [comment]
Why are you undoing the changes I made in https://github.com/Homebrew/homebrew-cask-drivers/pull/1771?

I tested this thoroughly when I submitted that PR?

**Comment by kostya740** [comment]
@miccal Could you please fixed comments out from @junian?
Thanks you

**Comment by miccal** [comment]
> @miccal Could you please fixed comments out from @junian?
> Thanks you

I do not understand what you are asking?

**Comment by kostya740** [comment]
> > @miccal Could you please fixed comments out from @junian?
> > Thanks you
> 
> I do not understand what you are asking?

Could you please fix comments from @junian and continue process the PR?

**Comment by miccal** [comment]
@kostya740 no, not until my question as to why this has been changed from my previous PR has been answered, and not until it passes our CI tests.

**Comment by miccal** [comment]
Install instructions included in a `readme.txt` insde the `.dmg`:

> INSTALL:
1.Click AX88179_178A_vX.X.X.dmg.
2.Click AX88179_178A_vX.X.X.app.
3.Follow the pkg install instruction (requires root privileges).
4.If your os version is 10.13 and later, you may get message "System Extension Blocked".
  Please go to "System Preferences -> Security & Privacy -> General" and click Allow button.
  (Allow button will disappear after 30 minutes.)
  https://developer.apple.com/library/archive/technotes/tn2459/_index.html
5.Reboot.
> 
> UNINSTALL:
1.Click AX88179_178A_vX.X.X.dmg.
2.Click "AX88179_178A_Uninstall_vX.X.X.pkg" (requires root privileges).

**Comment by junian** [comment]
Hi,

Sorry for the late reply.

The reason why I revert is because the script from v2.18.0 doesn't work for me.
It'll only put the installer into `/Applications/` directory, but the driver is not installed.

I tried using the script from v2.17.0 but replace it with v2.18.0 driver and it works just fine.

If this pull request feels inappropriate, I'll just close it.
Sorry about the trouble.

Kind regards.

**Comment by miccal** [comment]
@junian does running the `AX88179_178A_vX.X.X.app` install the driver as indicated in the `readme.txt`?

**Comment by kostya740** [comment]
@miccal your PR #1771 is not working. Because link https://www.asix.com.tw/FrootAttach/driver/AX88179_178A_macOS_10.9_to_10.15_Driver_Installer_v2.18.0.zip is not valid.
Need change to https://www.asix.com.tw/en/support/download/file/119
@miccal Please help @junian with this issue(PR).

**Comment by vitorgalvao** [comment]
> @miccal Could you please fixed comments out from @junian?
> (…)
> @miccal Please help @junian with this issue(PR).

Please stop pressuring. That doesn’t help. @miccal is doing whatever he cans and he always goes above and beyond with respect to this project, but he can only do so much without collaboration and users answering the questions.

I believe you mean well, but that kind of continuous pressure only brings volunteers closer to burnout.

**Comment by miccal** [comment]
Thank you @junian for your contribution to `homebrew-cask-drivers` and letting us know that there was an issue with this Cask.

Closing this in favour of https://github.com/Homebrew/homebrew-cask-drivers/pull/1844.

**Pull request closed without merging**
