### PR TITLE
Update apogee-duet to 2.5

### PR DESCRIPTION
**Pull request by ytbmulder**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by vitorgalvao** [comment]
Thank you for so many contributions to this repo. Any reason why you created such an affinity with the drivers repo (nothing to it, just curious)?

**Comment by ytbmulder** [comment]
> Thank you for so many contributions to this repo. Any reason why you created such an affinity with the drivers repo (nothing to it, just curious)?

I have been using Homebrew for quite a while and decided it was time to help contributing! This repo seems to get too little attention and I like the research that goes along with the addition of new casks. I have also been contributing to `homebrew-core` and `homebrew-cask` as well, but not as much as here.

**Comment by vitorgalvao** [comment]
> This repo seems to get too little attention

Your assessment is correct!

Thank you again for all the work!

**Comment by ytbmulder** [comment]
> Thank you again for all the work!

Happy to help!

**Pull request merged**
