### PR TITLE
Update drobo-dashboard to 3.4.0

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by vitorgalvao** [comment]
> uninstall script Uninstall.app/Contents/Resources/Scripts/Drobo_Dashboard_uninstall.sh does not exist.

**Comment by vitorgalvao** [comment]
Everything does indeed look to be in place. I’d like to try it with an install, but my VM software is no longer working.

@reitermarkus @claui Do any of you have the chance to check?

**Comment by ytbmulder** [comment]
@claui No problem, happy to help!

**Comment by vitorgalvao** [comment]
Thank you all.

**Pull request merged**
