### PR TITLE
Update canon-mf-printer from 10.11.6 to 10.11.8

### PR DESCRIPTION
**Pull request by cardoe**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by cardoe** [comment]
After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

**Comment by cardoe** [comment]
I would have used `brew bump-cask-pr` but it ignored the fact that the existing cask had `verified:` on the URL and complained the that the bumped version needed verified but there was no way to do it via CLI options.

**Comment by cardoe** [comment]
The only changelog from Canon is Monterey support but older versions still seem to support Monterey.

**Comment by cardoe** [comment]
```
╰─$ brew audit --cask canon-mf-printer
audit for canon-mf-printer: passed
```

when I run it locally. No error.

**Comment by bevanjkay** [comment]
@cardoe The checks are failing because the cask doesn't have a `livecheck`. 

CI uses `brew audit <token> --online`

**Comment by cardoe** [comment]
Thank you for the update. I wasn’t aware of how to do that.

**Pull request merged**
