### PR TITLE
sound-blaster-play3: update caveat

### PR DESCRIPTION
**Pull request by yurikoles**
Signed-off-by: Yurii Kolesnykov <root@yurikoles.com>

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.
---

@miccal, could you please help me with livechek?

### CODE REVIEW

**Comment by neutric** [comment]
@yurikoles What specifically do you need help with?

Starting point: you probably need separate `livecheck` blocks for the two different OS-version branches, so put them between `url` and `pkg` inside the conditional.

Mojave and older needs https://support.creative.com/downloads/welcome.aspx?nLanguageLocale=1033&nOS=14&nDriverType=0#type_0.

The other needs https://support.creative.com/downloads/welcome.aspx?nLanguageLocale=1033&nOS=25&nDriverType=0#type_0.

Then craft a regex that matches `SBP3_MAC_L13_2_00_03.dmg.zip` / `SBP3_MAC_L13_2_01_02.dmg` found in the source of the above urls.

Use the `livecheck` stanza from https://github.com/Homebrew/homebrew-cask/blob/master/Casks/dbschema.rb as an example, especially on how to deal with the underscores.

**Comment by sanyer** [comment]
Hi, I saw this discussion and decided to try.
Here is the working version:

```ruby
livecheck do
  url "https://support.creative.com/Products/ProductDetails.aspx?catID=1&subCatID=1258&prodID=23033"
  strategy :page_match do |page|
    v = if MacOS.version <= :mojave
      page[/SBP3[._-]MAC[._-]L13[._-]?(\d+(?:_\d+)+)\.dmg.zip/i, 1]
    else
      page[/SBP3[._-]MAC[._-]L13[._-]?(\d+(?:_\d+)+)\.dmg/i, 1]
    end
    next if v.blank?

    v.tr("_", ".")
  end
end
```

**Comment by neutric** [comment]
@sanyer Good job! Two thoughts: is the `.to_s` in `match[0].tr("_", ".").to_s` really needed? Multiple other casks seem fine without. Also, to be more future-proof with regards to `url` changes, I envisioned checking the OS version specific download pages that differ in the `nOS` parameter, but this can probably be tackled if the need ever arises. I'd rename `nos` to `ext` (like extension) in your version, though, and ditch the `( )` as they don't seem to be needed.

**Comment by yurikoles** [comment]
@neutric there were no updates for 2.5 years, they still didn't add support for Apple Silicon, which is available for mostly 2 years, if count from introduction of DTK. So `livecheck` in this cask is only needed to make linter happy.

**Comment by neutric** [comment]
```
Error: Some kernel extensions are still installed, add them to uninstall kext:
com.highpoint-tech.kext.HighPointIOP
com.highpoint-tech.kext.HighPointRR
com.softraid.driver.SoftRAID
```
This seems unrelated. CI was green on 1st commit, maybe because it ran on `10.15` whereas the 2nd commit ran on `11.0`?

**Comment by sanyer** [comment]
Hey @neutric , this `.to_s` was added by `brew style --fix` 🤷🏻‍♂️ 
Also, `nos` having conditional is also the result of `brew style --fix` :-)

**Comment by neutric** [comment]
@sanyer `brew style --fix" has no issues with the file as it is right now, that is, after implementing my suggestions. Not sure at which point in your efforts these two differences were introduced, but it seems they are not needed any more.

**Comment by neutric** [comment]
> @neutric great! I'm not a Ruby developer, so if you think it is better, I'm good :-)

Neither am I, but achieving the same with less code is good, isn't it?

**Comment by sanyer** [comment]
> Neither am I, but achieving the same with less code is good, isn't it?

It is, in most cases :-D
In this case, it definitely looks cleaner.
And since it works and (most probably) both this code's logic and webpage will never change, it's good.

**Comment by yurikoles** [comment]
Bump?

**Comment by yurikoles** [comment]
Guys, please review this PR.

**Pull request merged**
