### PR TITLE
Update flashforge-flashprint

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by suschizu** [comment]
```
 brew cask style36s
##[error]Process completed with exit code 1.
Run # don't care about `brew cask style` here.
Untapping adoptopenjdk/openjdk...
Untapped 37 casks (72 files, 406.5KB).
Error: Style check failed.
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/caldigit-thunderbolt-charging.rb ==
C: 16:119: Line is too long. [160/118]
```
okay … and what can we do here?

**Comment by miccal** [comment]
This has been fixed by https://github.com/Homebrew/brew/pull/8140 and https://github.com/Homebrew/homebrew-cask-drivers/pull/1675.

**Comment by suschizu** [comment]
really? I thought this was a joke … so each url that is longer than 160 characters has to receive a line break?
seems that some people still have very small … so back to the 80ies :/

**Comment by suschizu** [comment]
the lines in flashforge-flashprint aren#t too long - travis claims that some other casks has too long lines:
```
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/canon-ijscanner4.rb ==
C: 10:119: Line is too long. [146/118]
C: 12:119: Line is too long. [172/118]
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/canon-ijscanner5.rb ==
C: 10:119: Line is too long. [146/118]
C: 12:119: Line is too long. [172/118]
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/canon-ijscanner6.rb ==
C: 10:119: Line is too long. [146/118]
C: 12:119: Line is too long. [172/118]
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/microsoft-intellitype.rb ==
C:  9:119: Line is too long. [122/118]
== /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask-drivers/Casks/nvidia-web-driver.rb ==
```

**Comment by miccal** [comment]
All those ones have been fixed by the merging of https://github.com/Homebrew/brew/pull/8140.

**Comment by miccal** [comment]
> really? I thought this was a joke … so each url that is longer than 118 characters has to receive a line break?
> seems that some people still have very small screens … so back to the 80ies :/

[It is a GutHub thing](https://github.com/Homebrew/brew/blob/master/Library/.rubocop.yml#L179).

**Comment by miccal** [comment]
The last error will be fixed once https://github.com/Homebrew/homebrew-cask-drivers/pull/1675 is merged.

**Pull request merged**
