### PR TITLE
Update netgeargenie to 2.4.34

### PR DESCRIPTION
**Pull request by fibric**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [ ] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-drivers/pulls
[closed issues]: https://github.com/Homebrew/homebrew-cask-drivers/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by fibric** [comment]
According to `Named the cask according to the token reference.` this cask should be renamed to `netgear-genie` which I haven't done because I'm not the owner of this cask.

**Comment by vitorgalvao** [comment]
> which I haven't done because I'm not the owner of this cask

You may do so.  Casks don’t have owners.

**Comment by fibric** [comment]
What is the desired strategy for migrating cask names?
People who have `netgeargenie` installed, won't receive any update when I just rename the cask to `netgear-genie` - am I right? How can I ensure a smooth upgrade?

**Comment by commitay** [comment]
The installed app is `netgeargenie` so this doesn't need to be renamed.

**Pull request merged**
