### PR TITLE
Update wacom-tablet from 6.3.45-1 to 6.3.45-2

### PR DESCRIPTION
**Pull request by schlomo**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by schlomo** [comment]
I don't know what is the problem. When I install it locally on my Mac the Wacom utility shows me the correct version:
image

**Comment by bevanjkay** [comment]
@schlomo CI is failing because `livecheck` is reporting that the version found on upstream's website (https://www.wacom.com/en-us/support/product-support/drivers) is the previous version.

**Comment by schlomo** [comment]
Ah, I don't know why Wacom still advertises the old driver. However, Homebrew already has a newer driver `6.3.45-1` so that this livecheck problem should have appeared already back then.

However, https://cdn.wacom.com/u/productsupport/drivers/mac/professional/releasenotes/Mac_6.3.45.html states that the main change between `6.3.45-1` and `6.3.45-2` is actually **The Wacom Display Settings application no longer crashes when opened.** and I would like to believe that this is something worth having for the Homebrew users who **already** installed `6.3.45-1` which is newer than the version that Wacom advertises on their homepage.

Maybe Wacom lowered the recommended version when they noticed that `6.3.45-1` actually has a major problem and didn't bump it up again?

What do you think? The other consistent alternative - IMHO - would be for Homebrew to downgrade users if Wacom goes back to recommending an older version.

**Comment by bevanjkay** [comment]
@schlomo Generally we will point to the same release that upstream are distributing. So in this case, yes downgrading to match their homepage would be the way to go, until they push the newer version.

**Comment by schlomo** [comment]
I see. For M1 MacBook users that would be unfortunate as https://cdn.wacom.com/u/productsupport/drivers/mac/professional/releasenotes/Mac_6.3.45.html states about the `6.3.45-1` version that **The Wacom Display Settings application now works on a MacBook Pro with an M1 Pro or M1 Max processor.** and ** When using a MacBook Pro with an M1 Max processor, the pen calibration drop-down menu now populates correctly.** so that reverting to the previous version would be a step back to them compared to upgrading to the `6.3.45-2` version (which, BTW, works well for me on M1 Macbook Pro).

**Pull request merged**
