### PR TITLE
Update caldigit-docking-utility from 1.9.18 to 1.9.20

### PR DESCRIPTION
**Pull request by jabenninghoff**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by jabenninghoff** [comment]
I'm not sure why this failed, can someone help explain what needs to be fixed?

**Comment by reitermarkus** [comment]
Is there a page that lists the version? If so, add a `livecheck` block.

**Comment by jabenninghoff** [comment]
As far as I can tell, there is no page that lists the version, just the date of the latest release on the [downloads](https://downloads.caldigit.com) page.

The version only appears to exist in the name of the installer package. Is a 'skip' livecheck appropriate here?

**Comment by miccal** [comment]
Thank you @jabenninghoff.

**Review by miccal — APPROVED** [review]

**Pull request merged**
