### PR TITLE
Update corsair-icue from 3.27.68 to 3.28.70

### PR DESCRIPTION
**Pull request by suschizu**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by ran-dall** [comment]
@suschizu Can you look into why this is failing both CI checks?

**Comment by suschizu** [comment]
> @suschizu Can you look into why this is failing both CI checks?

ok I tried it but travis is failing too :(
 
audit for corsair-icue: failed
```
 - The URL https://www.corsair.com/us/en/downloads/search?searchCategory=Cor_Products_iCue_Compatibility is not reachable (HTTP status code 403)
 - The URL https://www.corsair.com/us/en/icue is not reachable (HTTP status code 403)
 - appcast at URL 'https://www.corsair.com/us/en/downloads/search?searchCategory=Cor_Products_iCue_Compatibility' does not contain the version number '3.28.70':
```
> just reachable via VPN

**Comment by suschizu** [comment]
Not sure what to do here
```
Failure while executing; `/usr/bin/sudo -E -- /usr/bin/osascript /Applications/Corsair/iCUEUninstaller.app/Contents/Scripts/uninstall.scpt` exited with 1. Here's the output:
/Applications/Corsair/iCUEUninstaller.app/Contents/Scripts/uninstall.scpt:261:265: execution error: Finder got an error: AppleEvent timed out. (-1712)
```

And these packages already exist in the categories:
```
Error: Some packages are still installed, add them to uninstall pkgutil:
com.corsair.CorsairAudio
com.corsair.cue.3
Error: Some launch jobs are still installed, add them to uninstall launchctl:
CorsairAudioConfigService (com.corsair.AudioConfigService.System)
iCUELaunchAgent (com.corsair.cue.3.launchHelper)
Error: Some applications are still running, add them to uninstall quit:
com.corsair.cue.3
Error: Build failed.

```

**Comment by ran-dall** [comment]
@suschizu Yeah that's a strange one. Originally, when I pinged you, I thought it might be something on Travis and GitHub Actions that made it time out. Thanks for testing it locally though.

**Comment by ran-dall** [comment]
@suschizu Do you know if the current version has this problem? I'm going to test it when I get back to my desk later but maybe the problem isn't there with the current version.

**Comment by suschizu** [comment]
let's wait for the next update

**Pull request closed without merging**
