### PR TITLE
Add live check to konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver

### PR DESCRIPTION
**Pull request by viking1304**
Based on konica-minolta-bizhub-c750i-driver implementation

**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

_In the following questions `<cask>` is the token of the cask you're submitting._

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://docs.brew.sh/Acceptable-Casks#stable-versions) or [documented exception](https://docs.brew.sh/Acceptable-Casks#but-there-is-no-stable-version).
- [x] `brew audit --cask --online <cask>` is error-free.
- [x] `brew style --fix <cask>` reports no offenses.

### CODE REVIEW

**Comment by viking1304** [comment]
Audit works fine on local machine

```
❯ brew audit --cask --appcast --online './Casks/konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver.rb'
==> Downloading https://dl.konicaminolta.eu/en/?tx_kmanacondaimport_downloadproxy[fileId]=7228bd01e7674417c6a223ce7a1864
######################################################################## 100.0%
audit for konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver: passed
```

but curl fails in CI 😒

```
Run brew audit --cask --appcast --online './Casks/konica-minolta-bizhub-c759-c65[8](https://github.com/Homebrew/homebrew-cask-drivers/actions/runs/3633189264/jobs/6129949155#step:12:9)-c368-c287-c3851-driver.rb'
audit for konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver: failed
 - exception while auditing konica-minolta-bizhub-c75[9](https://github.com/Homebrew/homebrew-cask-drivers/actions/runs/3633189264/jobs/6129949155#step:12:10)-c658-c368-c287-c3851-driver: curl: (28) Operation timed out after 15635 milliseconds with 128817 bytes received
Error: 1 problem in 1 cask detected
Error: exception while auditing konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver: curl: (28) Operation timed out after 15635 milliseconds with 128817 bytes received
Error: Process completed with exit code 1.
```

**Comment by viking1304** [comment]
I tried to rerun this CI on my fork a few more times, and I see in the logs that the audit always fails with a curl timeout (approximately after 15 seconds).

```
exception while auditing konica-minolta-bizhub-c759-c658-c368-c287-c3851-driver: curl: (28) 
Operation timed out after 15374 milliseconds with 137001 bytes received
```

Downloading from Minolta's server is **VERY SLOW**, and sometimes it takes more than 40 seconds on my Mac.

I saw that curl has a default **connect-timeout** set to 15 seconds in **utils/curl**, but I can't find any similar limit for **max-time**. Does anyone have any idea where this timeout comes from?

As I already wrote, auditing on my Mac succeeds without any problem.

**Comment by p-linnane** [comment]
This will need to be manually fixed for the new `on_system` blocks format.

**Comment by viking1304** [comment]
> This will need to be manually fixed for the new `on_system` blocks format.

Done!

**Comment by p-linnane** [comment]
@samford Any ideas on the `curl` issue here?

**Pull request closed without merging**
