### PR TITLE
lg-onscreen-control v3.06_patch2_08-Jun

### PR DESCRIPTION
**Pull request by denkristoffer**
I don't know if LG keeps changing their download URLs or what, but the existing URL gives me a 404. I got the new URL from https://www.lg.com/us/support-product/lg-27UK850-W#softwareFirmware

### CODE REVIEW

**Comment by denkristoffer** [comment]
Regarding https://travis-ci.org/Homebrew/homebrew-cask-drivers/builds/408050262#L451: Am I allowed to add a hostname comment myself or should a team member do it?

**Comment by vitorgalvao** [comment]
I still get 2.93 from the website. Where’s this version coming from?

> Am I allowed to add a hostname comment myself

You are. A maintainer will verify it.

**Comment by denkristoffer** [comment]
> I still get 2.93 from the website. Where’s this version coming from?

Maybe it depends on the monitor? LG's site seems to be outdated though, as you can see on https://www.lg.com/us/support-product/lg-27UK850-W#softwareFirmware it lists the version as 2.86 although it links to 3.06.

**Comment by vitorgalvao** [comment]
You’re linking to a specific monitor. I’m talking about the link in https://www.lg.com/us/support/monitors, which is where this cask links to. The cask referes to that file.

**Comment by core-code** [comment]
since pr #520 this was merged i think we can close this

**Comment by victorpopkov** [comment]
Completely agree. Let's close this one.

@denkristoffer Thank you, for your contribution! We really do appreciate all your time in making this PR.

**Pull request closed without merging**
