### PR TITLE
Add tiptoi® Manager Latest

### PR DESCRIPTION
**Pull request by JasperV**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
the download is not offered via https
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
I cannot run this locally as the dependencies do not install
- [x] The commit message includes the cask’s name and version.
- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not [already refused].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/Homebrew/homebrew-cask-drivers/pulls
[already refused]: https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues
[the correct repo]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by JasperV** [comment]
Hi, could you please help me with the remaining style issue? I cannot install the dependencies needed locally to do the style check. And I do not see why it keeps giving me the alignment error.

**Comment by ytbmulder** [comment]
> Hi, could you please help me with the remaining style issue? I cannot install the dependencies needed locally to do the style check. And I do not see why it keeps giving me the alignment error.

Hi @JasperV, thanks for your contribution. To fix the style offences, you should have only one space between the stanza and `:` character, like so:

```
  uninstall quit:     'com.ravensburger.tiptoimanager',
             delete:  '/Applications/tiptoi® Manager.app',
             pkgutil: [
                        'com.ravensburger.tiptoimanager',
                        'com.ravensburger.tiptoi.TipToiBindings',
                      ]
```

And align the other stanzas accordingly.

**Comment by JasperV** [comment]
Thanks, will update accordingly. 
The `delete` was required before, as the application is not removed.

**Comment by JasperV** [comment]
Also, now, it seems to work. But as mentioned the download file is not offered via https. Only via http. Is this really required?

**Comment by ytbmulder** [comment]
> Also, now, it seems to work. But as mentioned the download file is not offered via https. Only via http. Is this really required?

This is really required. Just change it to `https`. I can download the installer using Safari that way.

**Comment by ytbmulder** [comment]
@JasperV Looks good to me!

**Comment by vitorgalvao** [comment]
Thank you for the contribution, @JasperV.

And thank you for helping @JasperV, @ytbmulder!

**Pull request merged**
