### PR TITLE
Add Philips Hue Sync v1.0.0.3

### PR DESCRIPTION
**Pull request by boboldehampsink**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` reports no offenses.
- [x] The commit message includes the cask’s name and version.

Additionally, if **adding a new cask**:

- [x] Named the cask according to the [token reference].
- [x] `brew cask install {{cask_file}}` worked successfully.
- [x] `brew cask uninstall {{cask_file}}` worked successfully.
- [x] Checked there are no [open pull requests] for the same cask.
- [x] Checked the cask was not already refused in [closed issues].
- [x] Checked the cask is submitted to [the correct repo].

[token reference]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md
[open pull requests]: https://github.com/caskroom/homebrew-drivers/pulls
[closed issues]: https://github.com/caskroom/homebrew-drivers/issues?q=is%3Aissue+is%3Aclosed
[the correct repo]: https://github.com/caskroom/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask
[version-checksum]: https://github.com/caskroom/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/sha256.md#updating-the-sha256

### CODE REVIEW

**Comment by commitay** [comment]
@vitorgalvao We can either use `url do` here or add a preflight to hack around the file extension, not sure which one would be better?

**Comment by vitorgalvao** [comment]
Let’s hack the file extension because we have precedents ([example](https://github.com/Homebrew/homebrew-cask/blob/c778c9f30dab008e3a3d356d6dcc0486e243c924/Casks/xfinity-wifi.rb#L13L14)) and if we ever do improve the backend to cover those cases, we’ll also fix this one for free.

**Comment by commitay** [comment]
File extension hack doesn't seem to work with this, cask tries to unpack the download even if container `:pkg` is set.

**Comment by vitorgalvao** [comment]
> cask tries to unpack the download even if container `:pkg` is set.

What about `container type: naked`?

**Comment by commitay** [comment]
`naked` works.

**Pull request merged**
