### PR TITLE
Add PFU HHKB Pro Driver

### PR DESCRIPTION
**Pull request by diohabara**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).
- [x] `brew audit --cask {{cask_file}}` is error-free.
- [x] `brew style --fix {{cask_file}}` reports no offenses.

Additionally, **if adding a new cask**:

- [x] Named the cask according to the [token reference](https://github.com/Homebrew/homebrew-cask/blob/master/doc/cask_language_reference/token_reference.md).
- [x] Checked the cask was not [already refused](https://github.com/Homebrew/homebrew-cask-drivers/search?q=is%3Aclosed&type=Issues).
- [x] Checked the cask is submitted to [the correct repo](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask).
- [x] `brew audit --new-cask {{cask_file}}` worked successfully.
- [x] `brew install --cask {{cask_file}}` worked successfully.
- [x] `brew uninstall --cask {{cask_file}}` worked successfully.

### CODE REVIEW

**Comment by miccal** [comment]
Thank you for your contribution to `homebrew-cask-drivers` @diohabara.

Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

**Comment by diohabara** [comment]
> Thank you for your contribution to `homebrew-cask-drivers` @diohabara.
> 
> Could you please try to add a [`zap` stanza](https://github.com/homebrew/homebrew-cask/blob/master/doc/cask_language_reference/stanzas/zap.md), thanks.

Hi, thank you for your review!

When executing `brew cask createzap Casks/hhkb-pro-driver.rb`, I got the following result. Does this mean I don't need to do further actions for `zap` stanza?
```
No Casks/hhkb-pro-driver.rb settings found. 
```

**Comment by miccal** [comment]
I think you just need to run `brew cask createzap hhkb-pro-driver.rb`.

If that does not work, try running `sudo find / -iname "*{{search item}}*"` and inspecting what files and folders are output.

**Comment by diohabara** [comment]
@miccal 
Thank you for your advice.

- `brew cask createzap hhkb-pro-driver.rb` had the same result.
- `sudo find / -iname "*{{search item}}*"` differed. Its log is here. Some files are for my development environment. 

I think I don't need to add zap for this driver. Is it correct?
```
/usr/local/Caskroom/hhkb-pro-driver
/usr/local/Caskroom/hhkb-pro-driver/.metadata/5.0.1/20210110044021.656/Casks/hhkb-pro-driver.rb
/System/Volumes/Data/usr/local/Caskroom/hhkb-pro-driver
/System/Volumes/Data/usr/local/Caskroom/hhkb-pro-driver/.metadata/5.0.1/20210110044021.656/Casks/hhkb-pro-driver.rb
/System/Volumes/Data/Users/jio/Library/Caches/Homebrew/Cask/hhkb-pro-driver.rb--5.0.1.dmg
/System/Volumes/Data/Users/jio/Library/Caches/Homebrew/Cask/hhkb-pro-driver--5.0.1.dmg
/System/Volumes/Data/Users/jio/repo/github.com/diohabara/homebrew-cask-drivers/Casks/hhkb-pro-driver.rb
/Users/jio/Library/Caches/Homebrew/Cask/hhkb-pro-driver.rb--5.0.1.dmg
/Users/jio/Library/Caches/Homebrew/Cask/hhkb-pro-driver--5.0.1.dmg
/Users/jio/repo/github.com/diohabara/homebrew-cask-drivers/Casks/hhkb-pro-driver.rb
```

**Comment by miccal** [comment]
Have you actually installed this on your machine? You need to have the software installed to find any files to `zap`.

**Comment by diohabara** [comment]
As I said in the first comment, I should have successfully had the driver installed.

**Comment by diohabara** [comment]
`~/Library/Caches/Homebrew/Cask/hhkb-pro-driver--5.0.1.dmg`
Is this file to be removed by `zap`?

**Comment by miccal** [comment]
> `~/Library/Caches/Homebrew/Cask/hhkb-pro-driver--5.0.1.dmg`
> Is this file to be removed by `zap`?

No, `zap` should not remove anything stored in `homebrew` folders.

**Comment by diohabara** [comment]
This driver only requires installation of this dmg and openning the App, so I think no other files will remain.

**Comment by miccal** [comment]
Thank you @diohabara.

**Review by miccal — APPROVED** [review]

**Pull request merged**
