### PR TITLE
Update evolv-escribe-suite from 2_SP20 to 2_SP19

### PR DESCRIPTION
**Pull request by core-code**
After making all changes to the cask:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [x] The commit message includes the cask’s name and version.

### CODE REVIEW

**Comment by core-code** [comment]
thanks. note that i think its a bit questionable that the update to an unoffical version ( https://github.com/Homebrew/homebrew-cask-drivers/pull/883 ) was auto-merged by the bot. 

in any case, i've submitted the PR not to deliberately revert to stable, but because this download did not work any longer.

**Comment by vitorgalvao** [comment]
> note that i think its a bit questionable that the update to an unoffical version ( #883 )

How do you mean? It’s on their domain, why is it unofficial?

**Comment by core-code** [comment]
it was never linked on their homepage as was explained in the PR itself:

https://github.com/Homebrew/homebrew-cask-drivers/pull/883#issue-265610065

**Comment by vitorgalvao** [comment]
Ah, alright, I use “unofficial” in this context to mean “third-party”. [I’ve made a note to the submitter](https://github.com/Homebrew/homebrew-cask-drivers/pull/883#issuecomment-489351948).

**Comment by core-code** [comment]
ah sorry for the confusion. 

well, i don't blame the submitter, i blame the automerge -  but https://github.com/Homebrew/brew/pull/5972 is coming along slowly but surely ;)

**Pull request merged**
