### PR TITLE
Update segger-jlink from 7.20 to 7.20a

### PR DESCRIPTION
**Pull request by ShaharHD**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Review by carlocab — APPROVED** [review]

**Comment by ShaharHD** [comment]
@carlocab there's an issue with the `bump-cask-pr` command where it downloads the package incorrectly for some reason (and is why I need to fix the sha256 hash manually)

Where should I start to debug and fix this?

**Comment by carlocab** [comment]
What flags did you pass to `bump-cask-pr`?

**Comment by ShaharHD** [comment]
> What flags did you pass to `bump-cask-pr`? And what files did it download? If you can produce a reproducible test case, you can open an issue for it.

`brew bump-cask-pr --version 7.20a segger-jlink`

**Comment by carlocab** [comment]
Homebrew/brew.

**Pull request merged**
