### PR TITLE
Fix URL in HP Printer Drivers

### PR DESCRIPTION
**Pull request by krystof-k**
After making all changes to the cask:

- [ ] `brew cask audit --download {{cask_file}}` is error-free.
- [ ] `brew cask style --fix {{cask_file}}` reports no offenses.
- [ ] The commit message includes the cask’s name and version.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#finding-a-home-for-your-cask) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by krystof-k** [comment]
Apple deleted the file (Error 404). HP provides exactly the same.

**Comment by vitorgalvao** [comment]
The link on the page works, it’s just a different one: `https://updates.cdn-apple.com/2019/cert/041-88763-20191011-6e70f498-9d39-420c-b11b-b252b17233e2/HewlettPackardPrinterDrivers.dmg`

**Comment by krystof-k** [comment]
You're right. However maybe HP directly is a better source?

**Comment by vitorgalvao** [comment]
> However maybe HP directly is a better source?

That requires more changes to the cask, including changing its token. It’s best to just replace the URL.

**Comment by krystof-k** [comment]
All right, however the URL lacks the version now.

**Comment by vitorgalvao** [comment]
> however the URL lacks the version now.

Doesn’t matter: it’s unlikely Apple will update it, anyway.

**Pull request merged**
