### PR TITLE
Update sonos from 11.1 to 12.0

### PR DESCRIPTION
**Pull request by sal0max**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [X] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [X] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by sal0max** [comment]
Seems the Sonos homepage doesn't linkt to the new "S2" version, yet. However 12.0 was released today for Android, iOS and all other platforms and is the latest version.
Because the [download page](https://support.sonos.com/s/downloads) doesn't reflect that yet, the macupdater.net-appcast fails.

**Comment by silsha** [comment]
I think we should additionally create a sonos-s1 package. There will be some users who cannot upgrade to S2. (Or maybe sonos-s2 should be the additional package?)

**Comment by silsha** [comment]
The correct appcast-url for S2 is https://macupdater.net/cgi-bin/check_urls/check_url_redirect.cgi?url=https://www.sonos.com/en/redir/controller_software_mac2

**Comment by sal0max** [comment]
Good points!
I like to think of the S2 version of the new default one (as newer speakers need S2 to work), so this update still should be merged to the `sonos` cask. I fixed the appcast. Thanks for the link!

An addional S1 package should be made, yes. The question is: Should it be here, as e. g. `sonos-s1`, or should it be located in homebrew-cask-versions?

**Comment by core-code** [comment]
@vitorgalvao any ideas how to proceed here?

**Comment by vitorgalvao** [comment]
> Should it be here, as e. g. `sonos-s1`, or should it be located in homebrew-cask-versions?

The latter. Presumably all new speakers will require S2 and no new speakers requiring S1 will be made, which makes it effectively an older version.

**Pull request merged**
