### PR TITLE
Update droidcam-obs from 1.5.0 to 1.6.0

### PR DESCRIPTION
**Pull request by sataset**
v1.6.0+ work with obs 28+

---

Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by sataset** [comment]
So the new major OBS 28 version released and most plugins required major update. According to droidcam-obs [release notes](https://github.com/dev47apps/droidcam-obs-plugin/releases/tag/1.6.0):
- old `droidcam-obs` plugins <1.6.0 only work with `obs` cask <28.
- new >=1.6.0 plugins works only with obs >= 28


Download pages:
- official github downloads: https://github.com/dev47apps/droidcam-obs-plugin/releases
- official download page: https://www.dev47apps.com/obs/

**Comment by miccal** [comment]
Thank you @sataset.

**Review by miccal — APPROVED** [review]

**Comment by sataset** [comment]
You did most of the work:) 

However, should not be this added in order to preserve compatibility with OBS <28? I suppose this could be added straightaway as droidcam's github page have one file naming convention.

```
cask "droidcam-obs" do
  if obs.version >= 28
    version "1.6.0"
    sha256 "040e80cfe5469ae98f50206f58a218bc9efed36b11cafdc447659ed42e37988e"
  else
    version "1.5.0"
    sha256 "ae1ccf28b998f3cc8a7cbe63d43973cd3bc90a7abb590c6ee23cca278190090b"
  end
```

**Comment by bevanjkay** [comment]
@sataset We don't have a way to check the version of the dependent cask, so in this case we just point to the latest version.

**Pull request merged**
