### PR TITLE
Update lg-onscreen-control to 4.57,euFuiAS9q6s94WUKnkV2oA

### PR DESCRIPTION
**Pull request by AntonioMeireles**
Created with `brew bump-cask-pr`.

### CODE REVIEW

**Comment by AntonioMeireles** [comment]
FWIW, dunno where's latest failure coming from...

image

as locally everything builds / looks sane. (&& sorry noise about initial broken commit) 

Keep the great work and a great weekend!

**Comment by AntonioMeireles** [comment]
folks,

dunno, why this is failing under CI. at sight there must be something going on when trying to fetch the payload from lg's servers that does not go as expected.

**Comment by miccal** [comment]
@vitorgalvao not sure what is going on here -- the `url` downloads `Mac_OSC_4.57.zip` inside of which is `OSC_V4.57_signed.pkg`.

I tried a `container nested:` but it did not work.

**Comment by vitorgalvao** [comment]
I don’t have VMs to test if it works locally or if the failure is just on CI.

**Comment by AntonioMeireles** [comment]
@vitorgalvao 

hi!

> I don’t have VMs to test if it works locally or if the failure is just on CI.

fwiw, afaict failure is just under ci as locally, here, it builds and installs cleanly.

**Comment by miccal** [comment]
Thank you @AntonioMeireles.

**Review by miccal — APPROVED** [review]

**Comment by osteinhauer** [comment]
got SHA256 mismatch

```
==> Upgrading 1 outdated package:
lg-onscreen-control 4.40,hpiniL76TYo4uwCYNIHwQ -> 4.57,euFuiAS9q6s94WUKnkV2oA
==> Upgrading lg-onscreen-control
==> Downloading http://gscs-b2c.lge.com/downloadFile?fileId=euFuiAS9q6s94WUKnkV2
######################################################################## 100.0%
==> Purging files for version 4.57,euFuiAS9q6s94WUKnkV2oA of Cask lg-onscreen-co
Error: lg-onscreen-control: SHA256 mismatch
Expected: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
  Actual: 2b56f56ae99accc3c40efd6f194db214b2ad99bf2162152c0177f8a82bcbad12
    File: /Users/XXXXXX/Library/Caches/Homebrew/downloads/da66b6246f6c1cb7337f33dcabb4467818f40fdb8213fb0017fa1ac2c9bdc45e--Mac_OSC_4.57.zip
To retry an incomplete download, remove the file above.
```

**Comment by Bo98** [comment]
Also breaking `brew` CI:

```
audit for lg-onscreen-control: failed
 - cannot use the sha256 for an empty string: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

I'm going to try #2056 and see how CI goes.

**Pull request merged**
