### PR TITLE
Update fujitsu-scansnap-home from 1.7.0 to 1.8.0

### PR DESCRIPTION
**Pull request by suschizu**
**Important:** *Do not tick a checkbox if you haven’t performed its action.* Honesty is indispensable for a smooth review process.

After making all changes to a cask, verify:

- [x] `brew cask audit --download {{cask_file}}` is error-free.
- [x] `brew cask style --fix {{cask_file}}` left no offenses.
- [ ] There are no [open pull requests](https://github.com/Homebrew/homebrew-cask/pulls) for the same update.
- [ ] The submission is for [a stable version](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#stable-versions) or [documented exception](https://github.com/Homebrew/homebrew-cask/blob/master/doc/development/adding_a_cask.md#but-there-is-no-stable-version).

### CODE REVIEW

**Comment by miccal** [comment]
It appears that version 1.8.0 does not have an [offline installer](http://scansnap.fujitsu.com/global/dl/mac-sshoffline.html), and the `dmg` now contains `ScanSnap Home Setup.app` instead of a `pkg`, which I assume will now require an `installer manual:` and possibly an updated `uninstall`.

**Comment by suschizu** [comment]
hey @miccal - yes thanks - you are right - I think we had this situation before (https://github.com/Homebrew/homebrew-cask-drivers/commit/4b2e016a89a0cce050f912c7830a8acc4321a255#diff-654ad6181adb812ca14970369cc1be46) I think the offline installer will be published later

**Comment by core-code** [comment]
@parkerbxyz @suschizu @miccal i think we need to re-evaluate this. the offline installer is still at 1.7.0 from april. since then we've had versions 1.8.0, 1.8.1, 1.9.0 and are now at version 1.9.1 for the online installer. does it make sense to have the installer that is so far behind? should we carry both versions? neither?

**Comment by parkerbxyz** [comment]
@core-code Traditionally, the offline installer for the latest release has been made available two weeks after the online installer. I’m not sure why it fell so far behind this time, but given that most of the world was in crisis mode in and around April, I don’t blame them for falling behind. A new [offline installer](https://scansnap.fujitsu.com/global/dl/mac-sshoffline-q.html) for 1.9.1 was released today, so I’m hopeful this is a sign that things are back on track over at Fujitsu. I’ve opened a new PR to bump the version: https://github.com/Homebrew/homebrew-cask-drivers/pull/1917.

**Comment by core-code** [comment]
thanks for the PR! lets hope the situation improves now

**Pull request closed without merging**
